# Generated by Django 4.2.5 on 2023-09-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='task_photos', to='tasks.taskphoto'),
        ),
    ]
